server:
  servlet:
    session:
      cookie:
        same-site: none   # Cross-Origin 간 쿠키 전송 허용
        secure: true      # same-site가 none일 때 반드시 true여야 함 (HTTPS)
        http-only: true   # 보안을 위해 자바스크립트 접근 차단 권장

spring:
  application:
    name: linking

  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://gdg-5th-linking-db.clm2ko6ggpgl.ap-northeast-2.rds.amazonaws.com:3306/linking?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: ${RDS_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update # 엔티티 수정을 DB 테이블에 자동으로 반영해줍니다.
    show-sql: true     # 실행되는 SQL 쿼리를 터미널에 보여줍니다.
    properties:
      hibernate:
        format_sql: true


